### ISSUE TITLE
Master Issue for UX and Design of Nacto Care

### ISSUE THREAD

**Issue by Harshil-Jani** [Nactore-Org/Nacto-Care#1]
Please feel free to pick any of the below tasks.
I am very very bad at Designs and I need help to make the following look amazing and charming.

- [ ] Re-Write README in a beautiful language and also add emojis and posters.
- [ ] Create a Logo for Application
- [ ] Animation when the Application Starts
- [ ] UX Design Wireframes for the entire Application. Maybe on Figma.
- [ ] Inspiration to similar designs are also welcomed.

Add more thoughts ? I cannot think a lot in design and would add ideas as they come up while working.

**Comment by jcspacegirl** [comment]
Hello, I'd like to work specifically on the first task only (Re-Write README in a beautiful language and also add emojis and posters). Would that be possible? Also, may I kindly ask what you mean by 'beautiful language'? As well as what kind of posters are you looking for?

**Comment by Harshil-Jani** [comment]
@MehtabAsHellic Hii there, Please let me know what task would you love to undertake.

**Comment by Harshil-Jani** [comment]
@jcspacegirl Hey there, By 'beautiful language' I mean something which sounds correct and addresses the key goal. The project README should be able to keep the points clear and clean. 

Posters could be anything which represents Nacto-Care or Home caring or nurses. It could be an AI generated image or something which is restriction free and not copyrighted. However, Adding credits is an option and we totally don't mind adding the credits if the posters are work of somebody else.

Please let me know your thoughts for the same

**Comment by MehtabAsHellic** [comment]
> * Create a Logo for Application

 Create a Logo for Application
 UX Design Wireframes for the entire Application. Maybe on Figma.

**Comment by jcspacegirl** [comment]
> @jcspacegirl Hey there, By 'beautiful language' I mean something which sounds correct and addresses the key goal. The project README should be able to keep the points clear and clean.
> 
> Posters could be anything which represents Nacto-Care or Home caring or nurses. It could be an AI generated image or something which is restriction free and not copyrighted. However, Adding credits is an option and we totally don't mind adding the credits if the posters are work of somebody else.
> 
> Please let me know your thoughts for the same

Thank you for your reply, I have a better idea now. I would like to be assigned for this role and would like to work on this.

**Comment by DevjitSikdar** [comment]
Hello @Harshil-Jani I am GSSCOC Contributor . Excited about the prospect of designing the logo for Nacto Care. With a focus on precision and creativity, I'm committed to delivering top-tier results tailored to your needs. Let's collaborate for a standout logo that truly captures Nacto-Care's essence. Here is my Linkedin Profile : https://www.linkedin.com/in/devjitsikdar-3880451b7/
My potfolio : https://drive.google.com/drive/folders/1WmIpteVD6fXHR1dJkMJ-uAFxlMxYZdDn?usp=drive_link

**Comment by BrindaManani** [comment]
I would like to contribute in UX design wireframes for the entire application using Figma.
So kindly assign me this task.
